version: '3.8'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules  # Prevents overwriting node_modules in container
    ports:
      - "4200:4200"
    # command: "ng serve --host 0.0.0.0 --poll=2000 --port 4200 --disable-host-check"

    environment:
      - CHOKIDAR_USEPOLLING=true  # Needed for file watching in Docker
