name: Version Bump Check
on:
  push:
    branches:
      - main
jobs:
  version-bump-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Version Bump Check
        run: git diff origin/master HEAD -- package.json | grep version