name: Version Bump Check

on:
  push:
    branches:
      - main  # or 'master' depending on your default branch

jobs:
  version-bump-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full git history

      - name: Set PREV_SHA
        id: prev_sha
        run: echo "PREV_SHA=$(git rev-parse HEAD^)" >> "$GITHUB_ENV"

      - name: Version Bump Check
  run: |
    if ! git diff $PREV_SHA HEAD -- package.json | grep '"version"'; then
      echo "❌ Version not bumped in package.json!"
      exit 1
    fi

