name: Version Bump Check

on:
  push:
    branches:
      - main  # or 'master' depending on your default branch

jobs:
  version-bump-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full git history

      - name: Get previous commit
        id: prev_commit
        run: echo "PREV_SHA=$(git rev-parse HEAD^1)" >> $GITHUB_ENV

      - name: Check if version was bumped
        run: |
          if ! git diff ${{ env.PREV_SHA }} HEAD -- package.json | grep '"version"'; then
            echo "❌ Version not bumped in package.json!"
            exit 1
          fi
